# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=200)),
                ('charity_tag_1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.IntegerField(default=0)),
                ('donation_date', models.DateTimeField(verbose_name='date donated')),
                ('donation_impact', models.CharField(max_length=200)),
                ('donation_charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Charity')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Charity'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Donation'),
        ),
    ]
