# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='charity_tag_1',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donation_date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donation_impact',
        ),
    ]
