# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20171114_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='charity_name',
            field=models.CharField(max_length=200, null='TRUE'),
        ),
    ]
