# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20171114_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_charity',
            field=models.ForeignKey(null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='donations.Charity'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_donation',
            field=models.ForeignKey(null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='donations.Donation'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_amount',
            field=models.IntegerField(default=0, null='TRUE'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_charity',
            field=models.ForeignKey(null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='donations.Charity'),
        ),
    ]
