# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
