# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0009_auto_20171117_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_user',
            field=models.ForeignKey(null='TRUE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
