# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_auto_20171127_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='charity_cause',
            field=models.CharField(max_length=200, null='TRUE'),
        ),
        migrations.AddField(
            model_name='charity',
            name='charity_rating',
            field=models.IntegerField(default=0, null='TRUE'),
        ),
        migrations.AddField(
            model_name='charity',
            name='charity_tagline',
            field=models.CharField(max_length=200, null='TRUE'),
        ),
    ]
