# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_auto_20171222_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_donor',
            field=models.ForeignKey(null='TRUE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
